name: CINXS
on: 
  workflow_dispatch:
 
jobs:
  setup:
    runs-on: ubuntu-22.04
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
         server: [6233630]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
      - name: Setup on Port ${{matrix.server}}
        run: |
          docker -v
