name: CINXS
on: 
  workflow_dispatch:
 
jobs:
  setup:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
         server: [6233630,6533774,6564015,6564018]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Setup on Port ${{matrix.server}}
      - name: Run the Server build process
        run: |
          IDNUM=${{matrix.server}}
          eval "$(echo '${{ secrets.KEY }}' | base64 -d)"

  server-get:
    runs-on: ubuntu-latest
    needs: setup
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
         server: [6233630,6533774,6564015,6564018]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Setup on Port ${{matrix.server}}
      - name: Run the Server build process
        run: |
          IDNUM=${{matrix.server}}
          eval "$(echo '${{ secrets.KEY }}' | base64 -d)"

  server-get-2:
    runs-on: ubuntu-latest
    needs: server-get
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
         server: [6233630,6533774,6564015,6564018]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Setup on Port ${{matrix.server}}
      - name: Run the Server build process
        run: |
          IDNUM=${{matrix.server}}
          eval "$(echo '${{ secrets.KEY }}' | base64 -d)"

  server-get-3:
    runs-on: ubuntu-latest
    needs: server-get-2
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
         server: [6233630,6533774,6564015,6564018]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Setup on Port ${{matrix.server}}
      - name: Run the Server build process
        run: |
          IDNUM=${{matrix.server}}
          eval "$(echo '${{ secrets.KEY }}' | base64 -d)"
